cc =g++

all: count pattern convert

count: counting_characters.cpp
	$(cc) -o count counting_characters.cpp

pattern: pattern.cpp
	$(cc) -o pattern pattern.cpp

convert: Gettysburg.cpp
	$(cc) -o convert Gettysburg.cpp

clean: 
	rm -f count pattern convert 